# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Modules/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(596, 279)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.phrase_label = QtWidgets.QLabel(self.centralwidget)
        self.phrase_label.setGeometry(QtCore.QRect(130, 256, 461, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.phrase_label.setFont(font)
        self.phrase_label.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.phrase_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.phrase_label.setAlignment(QtCore.Qt.AlignCenter)
        self.phrase_label.setObjectName("phrase_label")
        self.name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_edit.setGeometry(QtCore.QRect(10, 30, 111, 20))
        self.name_edit.setText("")
        self.name_edit.setObjectName("name_edit")
        self.surname_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.surname_edit.setEnabled(True)
        self.surname_edit.setGeometry(QtCore.QRect(10, 80, 111, 20))
        self.surname_edit.setText("")
        self.surname_edit.setObjectName("surname_edit")
        self.prof_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.prof_edit.setGeometry(QtCore.QRect(10, 130, 111, 20))
        self.prof_edit.setText("")
        self.prof_edit.setObjectName("prof_edit")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(10, 160, 51, 41))
        self.add_btn.setObjectName("add_btn")
        self.del_btn = QtWidgets.QPushButton(self.centralwidget)
        self.del_btn.setGeometry(QtCore.QRect(70, 160, 51, 41))
        self.del_btn.setObjectName("del_btn")
        self.cls_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cls_btn.setGeometry(QtCore.QRect(10, 210, 51, 41))
        self.cls_btn.setObjectName("cls_btn")
        self.fnd_btn = QtWidgets.QPushButton(self.centralwidget)
        self.fnd_btn.setGeometry(QtCore.QRect(70, 210, 51, 41))
        self.fnd_btn.setObjectName("fnd_btn")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.name_label.setObjectName("name_label")
        self.surname_label = QtWidgets.QLabel(self.centralwidget)
        self.surname_label.setGeometry(QtCore.QRect(10, 60, 61, 16))
        self.surname_label.setObjectName("surname_label")
        self.prof__label = QtWidgets.QLabel(self.centralwidget)
        self.prof__label.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.prof__label.setObjectName("prof__label")
        self.list_widget = QtWidgets.QListWidget(self.centralwidget)
        self.list_widget.setGeometry(QtCore.QRect(130, 10, 461, 241))
        self.list_widget.setObjectName("list_widget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "User Manager"))
        self.phrase_label.setText(_translate("MainWindow", "Dude, you can register here and search for your bro"))
        self.add_btn.setText(_translate("MainWindow", "Add"))
        self.del_btn.setText(_translate("MainWindow", "Del"))
        self.cls_btn.setText(_translate("MainWindow", "Cls"))
        self.fnd_btn.setText(_translate("MainWindow", "Fnd"))
        self.name_label.setText(_translate("MainWindow", "Name"))
        self.surname_label.setText(_translate("MainWindow", "Surname"))
        self.prof__label.setText(_translate("MainWindow", "Profession"))
